;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        indent-for-tab-command
        indent-new-comment-line
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-kill-line
        org-return-indent
        org-self-insert-command
        org-yank
        sp--self-insert-command
        sp-remove-active-pair-overlay
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        ace-jump-done
        ace-jump-word-mode
        compilation-next-error
        end-of-buffer
        find-tag
        kill-region
        m-test-current-buffer-file
        org-forward-paragraph
        query-replace
        show-entry
        spin-push-current-buffer-file
        toggle-should
        undefined
        ))
