(source melpa)
(source marmalade)
(source gnu)

(depends-on "[cl-struct-package-desc ace-jump-mode (20130720 1153) a quick cursor location minor mode for emacs [github] nil single melpa nil nil nil]")
(depends-on "[cl-struct-package-desc ag (20130924 1453) A front-end for ag ('the silver searcher'), the C ack replacement. [github] nil single melpa nil nil nil]")
(depends-on "[cl-struct-package-desc auto-complete (20130724 1750) Auto Completion for GNU Emacs [github] ((popup (0 5 0))) tar melpa nil nil nil]")
(depends-on "[cl-struct-package-desc cask (20131021 840) Cask: Emacs dependency management made easy [github] ((s (1 8 0)) (dash (2 2 0)) (f (0 10 0)) (epl (0 0 1))) tar melpa nil nil nil]")
(depends-on "[cl-struct-package-desc enh-ruby-mode (20130916 1412) Major mode for editing Ruby files [github] nil tar melpa nil nil nil]")
(depends-on "[cl-struct-package-desc ess (20131027 2006) No description available. [github] nil tar melpa nil nil nil]")
(depends-on "[cl-struct-package-desc git-commit-mode (20131013 555) Major mode for editing git commit messages [github] nil single melpa nil nil nil]")
(depends-on "[cl-struct-package-desc git-gutter (20131002 1856) Port of Sublime Text plugin GitGutter [github] nil single melpa nil nil nil]")
(depends-on "[cl-struct-package-desc git-rebase-mode (20131005 1730) Major mode for editing git rebase files [github] nil single melpa nil nil nil]")
(depends-on "[cl-struct-package-desc go-mode (20131022 1235) Major mode for the Go programming language [hg] nil tar melpa nil nil nil]")
(depends-on "[cl-struct-package-desc grizzl (20130810 1902) Fuzzy Search Library & Completing Read [github] ((cl-lib (0 1))) tar melpa nil nil nil]")
(depends-on "[cl-struct-package-desc ido-better-flex (0 0 2) A better flex (fuzzy) algorithm for Ido. nil single marmalade nil nil nil]")
(depends-on "[cl-struct-package-desc js2-mode (20131018 858) Improved JavaScript editing mode [github] ((emacs (24 1))) tar melpa nil nil nil]")
(depends-on "[cl-struct-package-desc key-chord (20080915 2156) map pairs of simultaneously pressed keys to commands [wiki] nil single melpa nil nil nil]")
(depends-on "[cl-struct-package-desc magit (20131026 1235) control Git from Emacs [github] ((cl-lib (0 3)) (git-commit-mode (0 14 0)) (git-rebase-mode (0 14 0))) tar melpa nil nil nil]")
(depends-on "[cl-struct-package-desc mmm-mode (20131028 139) Allow Multiple Major Modes in a buffer [github] nil tar melpa nil nil nil]")
(depends-on "[cl-struct-package-desc multi-web-mode (20130824 54) multiple major mode support for web editing [github] nil tar melpa nil nil nil]")
(depends-on "[cl-struct-package-desc multiple-cursors (20131031 2138) Multiple cursors for Emacs. [github] nil tar melpa nil nil nil]")
(depends-on "[cl-struct-package-desc no-easy-keys (1 0 2) Learn the proper Emacs movement keys nil single marmalade nil nil nil]")
(depends-on "[cl-struct-package-desc pallet (20130926 1940) A package management tool for Emacs, using Cask. [github] ((cask (0 4 6))) tar melpa nil nil nil]")
(depends-on "[cl-struct-package-desc php-mode (20130920 1850) Major mode for editing PHP code [github] nil single melpa nil nil nil]")
(depends-on "[cl-struct-package-desc pkg-info (20131020 1746) Information about packages [github] ((dash (1 6 0)) (epl (0 1))) single melpa nil nil nil]")
(depends-on "[cl-struct-package-desc projectile (20131018 1037) Manage and navigate projects in Emacs easily [github] ((s (1 6 0)) (dash (1 5 0)) (pkg-info (0 1))) single melpa nil nil nil]")
(depends-on "[cl-struct-package-desc psgml (1 4 1) Lennart Staflin's Psgml package, with Elisp syntax and sgml-validate fixed for Emacsen >=24. nil tar marmalade nil nil nil]")
(depends-on "[cl-struct-package-desc rhtml-mode (20130421 1008) major mode for editing RHTML files [github] nil tar melpa nil nil nil]")
(depends-on "[cl-struct-package-desc rinari (20131006 1006) Rinari Is Not A Rails IDE [github] ((ruby-mode (1 0)) (inf-ruby (2 2 5)) (ruby-compilation (0 16)) (jump (2 0))) single melpa nil nil nil]")
(depends-on "[cl-struct-package-desc robe (20131106 151) Code navigation, documentation lookup and completion for Ruby [github] ((inf-ruby (2 3 0))) tar melpa nil nil nil]")
(depends-on "[cl-struct-package-desc scala-mode2 (20131023 1455) Major mode for editing Scala >= 2.9 [github] nil tar melpa nil nil nil]")
(depends-on "[cl-struct-package-desc smex (20130707 1255) M-x interface with Ido-style fuzzy matching. [github] nil single melpa nil nil nil]")
(depends-on "[cl-struct-package-desc undo-tree (20130812 1224) Treat undo history as a tree [git] nil single melpa nil nil nil]")
(depends-on "[cl-struct-package-desc web-mode (20131104 1912) major mode for editing html templates [github] nil tar melpa nil nil nil]")
(depends-on "[cl-struct-package-desc wgrep (20130723 2134) Writable grep buffer and apply the changes to files [github] nil single melpa nil nil nil]")
(depends-on "[cl-struct-package-desc zenburn-theme (20131014 1537) A low contrast color theme for Emacs. [github] nil single melpa nil nil nil]")
(depends-on "ace-jump-mode")
(depends-on "ag")
(depends-on "auto-complete")
(depends-on "cask")
(depends-on "cl-lib")
(depends-on "company")
(depends-on "ctags")
(depends-on "dash")
(depends-on "enh-ruby-mode")
(depends-on "epl")
(depends-on "ess")
(depends-on "f")
(depends-on "git-commit-mode")
(depends-on "git-gutter")
(depends-on "git-rebase-mode")
(depends-on "go-mode")
(depends-on "grizzl")
(depends-on "helm")
(depends-on "helm-ag")
(depends-on "helm-projectile")
(depends-on "helm-rb")
(depends-on "helm-rubygems-local")
(depends-on "ido-better-flex")
(depends-on "js2-mode")
(depends-on "key-chord")
(depends-on "magit")
(depends-on "mmm-mode")
(depends-on "multi-web-mode")
(depends-on "multiple-cursors")
(depends-on "pallet")
(depends-on "php-mode")
(depends-on "pkg-info")
(depends-on "popup")
(depends-on "projectile")
(depends-on "psgml")
(depends-on "rinari")
(depends-on "robe")
(depends-on "rubocop")
(depends-on "s")
(depends-on "scala-mode2")
(depends-on "smex")
(depends-on "undo-tree")
(depends-on "web-mode")
(depends-on "wgrep")
(depends-on "yaml-mode")
(depends-on "zenburn-theme")